/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_0b7d3bae (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/wwpvntmueafieessgnbu/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0b7d3bae").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_0b7d3bae").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0b7d3bae").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0b7d3bae").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_0b7d3bae").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_0b7d3bae").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// key와 value를 함께 반환하는 prefix 조회 (페이지네이션으로 max-rows 제한 우회)
export const getByPrefixWithKeys = async (prefix: string): Promise<{key: string, value: any}[]> => {
  const supabase = client();
  // PostgREST max-rows = 1000이므로 pageSize를 999로 설정해 pagination이 작동하도록 함
  const pageSize = 999;
  const all: {key: string, value: any}[] = [];
  let from = 0;
  while (true) {
    const { data, error } = await supabase.from("kv_store_0b7d3bae")
      .select("key, value").like("key", prefix + "%")
      .order("key", { ascending: false })
      .range(from, from + pageSize - 1);
    if (error) throw new Error(error.message);
    if (!data?.length) break;
    all.push(...data);
    if (data.length < pageSize) break;
    from += pageSize;
  }
  return all;
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const items = await getByPrefixWithKeys(prefix);
  return items.map((d) => d.value);
};

// prefix + JSONB 최상위 필드값으로 DB에서 직접 필터링해 조회한다.
// 전체 스캔(모든 행을 함수로 가져와 JS에서 필터) 대신 매칭 행만 전송받아 전송량/파싱을 최소화한다.
// (value->>field) 인덱스가 있으면 더 빨라지고, 없어도 서버측 필터라 전체 fetch보다 훨씬 저렴하다.
export const getByPrefixWhereField = async (
  prefix: string, field: string, value: string,
): Promise<{ key: string, value: any }[]> => {
  const supabase = client();
  const pageSize = 999;
  const all: { key: string, value: any }[] = [];
  let from = 0;
  while (true) {
    const { data, error } = await supabase.from("kv_store_0b7d3bae")
      .select("key, value").like("key", prefix + "%")
      .filter(`value->>${field}`, "eq", value)
      .order("key", { ascending: false })
      .range(from, from + pageSize - 1);
    if (error) throw new Error(error.message);
    if (!data?.length) break;
    all.push(...data);
    if (data.length < pageSize) break;
    from += pageSize;
  }
  return all;
};